-- Standardize existing participant districts before enforcing the 64 choices.
-- FTC 340's "Dhaja" -> "Dhaka" was confirmed by the roster owner.
BEGIN;
CREATE TEMP TABLE district_map (alias text PRIMARY KEY, canonical text NOT NULL) ON COMMIT DROP;
INSERT INTO district_map (alias, canonical) VALUES
    ('bagerhat', 'Bagerhat'),
    ('bandarban', 'Bandarban'),
    ('barguna', 'Barguna'),
    ('barisal', 'Barishal'),
    ('barishal', 'Barishal'),
    ('bhola', 'Bhola'),
    ('bogura', 'Bogura'),
    ('brahmanbaria', 'Brahmanbaria'),
    ('chandpur', 'Chandpur'),
    ('chapainawabganj', 'Chapainawabganj'),
    ('chattogram', 'Chattogram'),
    ('chittagong', 'Chattogram'),
    ('chuadanga', 'Chuadanga'),
    ('comilla', 'Cumilla'),
    ('cox''s bazar', 'Cox''s Bazar'),
    ('cox''sbazar', 'Cox''s Bazar'),
    ('cumilla', 'Cumilla'),
    ('dhaja', 'Dhaka'),
    ('dhaka', 'Dhaka'),
    ('dinajpur', 'Dinajpur'),
    ('faridpur', 'Faridpur'),
    ('feni', 'Feni'),
    ('gaibandha', 'Gaibandha'),
    ('gazipur', 'Gazipur'),
    ('gopalganj', 'Gopalganj'),
    ('gopalgonj', 'Gopalganj'),
    ('habiganj', 'Habiganj'),
    ('habigonj', 'Habiganj'),
    ('irangpur', 'Rangpur'),
    ('jamalpur', 'Jamalpur'),
    ('jashore', 'Jashore'),
    ('jessore', 'Jashore'),
    ('jhalakathi', 'Jhalakathi'),
    ('jhalokathi', 'Jhalakathi'),
    ('jhalokati', 'Jhalakathi'),
    ('jhenaidah', 'Jhenaidah'),
    ('joypurhat', 'Joypurhat'),
    ('khagrachari', 'Khagrachhari'),
    ('khagrachhari', 'Khagrachhari'),
    ('khulna', 'Khulna'),
    ('kishoreganj', 'Kishoreganj'),
    ('kishoregonj', 'Kishoreganj'),
    ('kurigram', 'Kurigram'),
    ('kushtia', 'Kushtia'),
    ('lakshmipur', 'Lakshmipur'),
    ('lalmonirhat', 'Lalmonirhat'),
    ('laxmipur', 'Lakshmipur'),
    ('madaripur', 'Madaripur'),
    ('magura', 'Magura'),
    ('manikganj', 'Manikganj'),
    ('meherpur', 'Meherpur'),
    ('moulvibazar', 'Moulvibazar'),
    ('munshiganj', 'Munshiganj'),
    ('mymensingh', 'Mymensingh'),
    ('naogao', 'Naogaon'),
    ('naogaon', 'Naogaon'),
    ('narail', 'Narail'),
    ('narayanganj', 'Narayanganj'),
    ('naraynaganj', 'Narayanganj'),
    ('narshandi', 'Narsingdi'),
    ('narshingdi', 'Narsingdi'),
    ('narsingdi', 'Narsingdi'),
    ('narsongdi', 'Narsingdi'),
    ('natore', 'Natore'),
    ('neteokona', 'Netrakona'),
    ('netrakona', 'Netrakona'),
    ('netrokona', 'Netrakona'),
    ('nilphamari', 'Nilphamari'),
    ('noagaon', 'Naogaon'),
    ('noakhali', 'Noakhali'),
    ('pabna', 'Pabna'),
    ('panchagarh', 'Panchagarh'),
    ('patuakhali', 'Patuakhali'),
    ('pirojpur', 'Pirojpur'),
    ('rajbari', 'Rajbari'),
    ('rajshahi', 'Rajshahi'),
    ('rajshashi', 'Rajshahi'),
    ('rangamati', 'Rangamati'),
    ('rangpur', 'Rangpur'),
    ('satkhira', 'Satkhira'),
    ('shariatpur', 'Shariatpur'),
    ('sherpur', 'Sherpur'),
    ('sirajganj', 'Sirajganj'),
    ('sunamganj', 'Sunamganj'),
    ('sylhet', 'Sylhet'),
    ('tangail', 'Tangail'),
    ('thakurgaon', 'Thakurgaon');

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM members m
    LEFT JOIN district_map d ON lower(btrim(m.home_district)) = d.alias
    WHERE d.alias IS NULL
  ) THEN
    RAISE EXCEPTION 'Unmapped member home district; review roster before applying migration';
  END IF;
END $$;

UPDATE members m SET home_district = d.canonical
FROM district_map d
WHERE lower(btrim(m.home_district)) = d.alias
  AND m.home_district IS DISTINCT FROM d.canonical;

ALTER TABLE members ADD CONSTRAINT members_home_district_known
CHECK (home_district IN (
    'Bagerhat',
    'Bandarban',
    'Barguna',
    'Barishal',
    'Bhola',
    'Bogura',
    'Brahmanbaria',
    'Chandpur',
    'Chapainawabganj',
    'Chattogram',
    'Chuadanga',
    'Cox''s Bazar',
    'Cumilla',
    'Dhaka',
    'Dinajpur',
    'Faridpur',
    'Feni',
    'Gaibandha',
    'Gazipur',
    'Gopalganj',
    'Habiganj',
    'Jamalpur',
    'Jashore',
    'Jhalakathi',
    'Jhenaidah',
    'Joypurhat',
    'Khagrachhari',
    'Khulna',
    'Kishoreganj',
    'Kurigram',
    'Kushtia',
    'Lakshmipur',
    'Lalmonirhat',
    'Madaripur',
    'Magura',
    'Manikganj',
    'Meherpur',
    'Moulvibazar',
    'Munshiganj',
    'Mymensingh',
    'Naogaon',
    'Narail',
    'Narayanganj',
    'Narsingdi',
    'Natore',
    'Netrakona',
    'Nilphamari',
    'Noakhali',
    'Pabna',
    'Panchagarh',
    'Patuakhali',
    'Pirojpur',
    'Rajbari',
    'Rajshahi',
    'Rangamati',
    'Rangpur',
    'Satkhira',
    'Shariatpur',
    'Sherpur',
    'Sirajganj',
    'Sunamganj',
    'Sylhet',
    'Tangail',
    'Thakurgaon'
));
COMMIT;
